### ISSUE TITLE
CLI crashes randomly when several commands are sent in a row

### ISSUE THREAD

**Issue by GeremWD** [ditrit/OGrEE-CLI#164]
```
+rack:/P/BNPP/MD/1SS/Serveurs1/R09 @ [ 4, 4] @ [60,80,47]@front
Error: stream error: stream ID 121; INTERNAL_ERROR; received from peer
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
cli/controllers.GetObject({0xc0000942d0, 0x1f}, 0x1)
        /OGrEE/OGrEE-CLI/controllers/commandController.go:272 +0x37b
cli/controllers.GetOCLIAtrributes({0xc0000942d0, 0x23}, 0x4, 0xa?)
        /OGrEE/OGrEE-CLI/controllers/commandController.go:1370 +0x335
main.(*createRackNode).execute(0xc000432600)
        /OGrEE/OGrEE-CLI/ast.go:1152 +0x4ca
main.InterpretLine({0xc0001e9f40?, 0xc00000a018?})
        /OGrEE/OGrEE-CLI/repl.go:30 +0x4e
main.ExecuteFile(0xc000469868, {0xc0001e9680, 0x34})
        /OGrEE/OGrEE-CLI/ocli.go:45 +0x1a5
main.LoadFile({0xc0001e9680, 0x34})
        /OGrEE/OGrEE-CLI/ocli.go:88 +0x25d
main.ExecuteFile(0xc000469a40, {0xc0001e9486, 0x2c})
        /OGrEE/OGrEE-CLI/ocli.go:51 +0x1f1
main.LoadFile({0xc0001e9486, 0x2c})
        /OGrEE/OGrEE-CLI/ocli.go:88 +0x25d
main.Repl(0xc000008780, {0xc000015030, 0x6})
        /OGrEE/OGrEE-CLI/repl.go:111 +0x17a
main.Start(0xc000119ee8)
        /OGrEE/OGrEE-CLI/repl.go:102 +0x7ed
main.main()
        /OGrEE/OGrEE-CLI/main.go:92 +0xae5
      
```

**Comment by hchybz** [comment]
ce genre de trucs fonctionne chez moi j'ai testé hier avec cédric des dizaines de fois 
```
toto@OGrEE3D:/Physical$> undraw /P/BNPP ; - /Logical/BldgTemplates/bnpp-md-1ss
toto@OGrEE3D:/Physical$> .template:${CUST}/BNPP.MDcopy.json ; draw /P/BNPP 4 ;  camera.move=[-1.86,-55.23,6.29]@[62,-26]
```

**Comment by denizul** [comment]
This is linked with issue 54 (https://github.com/ditrit/OGrEE-Core/issues/36)
