### ISSUE TITLE
Focus command crash

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#70]
- [x] Crash with unknown path
```
cedrok@OGrEE3D:/Physical$> >patate
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
cli/controllers.FocusUI({0xc0000173c0?, 0x0?})
        /OGrEE/OGrEE-CLI/controllers/commandController.go:2057 +0x1a7
main.(*focusNode).execute(0x0?)
        /OGrEE/OGrEE-CLI/ast.go:175 +0x45
main.(*ast).execute(0xc00000e900)
        /OGrEE/OGrEE-CLI/ast.go:41 +0x69
main.InterpretLine(0xc00023e000?)
        /OGrEE/OGrEE-CLI/repl.go:28 +0xc2
main.Repl(0xc00000e228, {0xc00001a0c5, 0x6})
        /OGrEE/OGrEE-CLI/repl.go:108 +0x1af
main.Start(0x6ec2a0?)
        /OGrEE/OGrEE-CLI/repl.go:92 +0x5c9
main.main()
        /OGrEE/OGrEE-CLI/main.go:109 +0x187e
```

- [x] Should work with empty path to unfocus in 3D client
It should send : 
```json
{"data":"","type":"focus"}
```

**Comment by denizul** [comment]
Resolved on dev branch as of 759e545
